#!/bin/bash
# ==============================================================================
#   HPB-AI Server Deployment Script — Shared Tomcat Edition
#
#   Deploys HPB-AI the way it actually runs on this server: as a WAR file
#   swapped into the existing, shared Tomcat instance that also hosts other
#   KI apps (nkcx, dev-vac-admin, dev-follow-up, ...) behind the Apache
#   reverse proxy that's already configured for this hostname. This avoids
#   ever needing a new port opened by IT.
#
#   DO NOT EDIT THIS FILE. All settings live in hpb_deploy.config, in the
#   same folder as this script. Edit that file instead.
#
#   IMPORTANT — things this script deliberately does NOT do:
#     * It never restarts tomcat.service itself (that would take down every
#       other app sharing this Tomcat) -- it only ever replaces this app's
#       one WAR file, which Tomcat auto-redeploys within ~30 seconds.
#     * It never populates synthetic/test patient data. That stays a manual,
#       documented step (see the deployment runbook, Part D) so nobody runs
#       it by accident on a server with real data.
#     * The one-time Apache reverse-proxy config (the vhost file that routes
#       this hostname to Tomcat + the AI agent) is NOT set up by this script.
#       That's a one-time, per-server step -- see the runbook, Part C.
#
#   Usage:
#     ./deploy_hpb_tomcat.sh                        Routine redeploy, keeps
#                                                    existing database data.
#     ./deploy_hpb_tomcat.sh --reset-db             Same, but wipes and
#                                                    recreates the database
#                                                    first (first-time setup
#                                                    on a brand new server).
#     ./deploy_hpb_tomcat.sh --skip-pull            Deploy whatever is
#                                                    already checked out on
#                                                    disk, without pulling
#                                                    from git first.
#     ./deploy_hpb_tomcat.sh --restart-services-only
#                                                    Don't touch git, the
#                                                    build, or Tomcat at all
#                                                    -- just restart the AI
#                                                    agent + report-parsing
#                                                    sidecar. Use this after
#                                                    a server reboot: Tomcat
#                                                    comes back on its own
#                                                    via systemd, but these
#                                                    two background Python
#                                                    processes do not.
#     ./deploy_hpb_tomcat.sh --backend claude       Use the Claude API
#                                                    backend instead of the
#                                                    local Ollama model.
#
#   Before first run: chmod +x deploy_hpb_tomcat.sh
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/hpb_deploy.config"

# ── STEP 0: Load configuration ────────────────────────────────────────────
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Config file not found: $CONFIG_FILE"
  echo "   Make sure hpb_deploy.config is in the same folder as this script."
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

[ -n "$BACKEND" ] || BACKEND="ollama"
[ -n "$ENABLE_AI_ASSISTANT" ] || ENABLE_AI_ASSISTANT="true"
[ -n "$MOLECULAR_AGENT_DIR" ] || MOLECULAR_AGENT_DIR="$PARENT_DIR/molecular_report_agent"
[ -n "$MOLECULAR_SIDECAR_PORT" ] || MOLECULAR_SIDECAR_PORT=8090
[ -n "$TOMCAT_WEBAPPS_DIR" ] || { echo "❌ TOMCAT_WEBAPPS_DIR not set in hpb_deploy.config."; exit 1; }
[ -n "$TOMCAT_WAR_NAME" ] || { echo "❌ TOMCAT_WAR_NAME not set in hpb_deploy.config."; exit 1; }
[ -n "$CATALINA_LOG" ] || { echo "❌ CATALINA_LOG not set in hpb_deploy.config."; exit 1; }
[ -n "$TOMCAT_PORT" ] || TOMCAT_PORT=8080

if [ "$MYSQL_PASSWORD" = "CHANGE_ME_TO_A_STRONG_PASSWORD" ] || [ -z "$MYSQL_PASSWORD" ]; then
  echo "❌ MYSQL_PASSWORD in hpb_deploy.config is still the placeholder value."
  exit 1
fi
if [ -z "$HPB_APP_REPO" ] || [ -z "$AI_AGENT_REPO" ] || [ -z "$DEPLOY_ASSETS_REPO" ]; then
  echo "❌ HPB_APP_REPO / AI_AGENT_REPO / DEPLOY_ASSETS_REPO must all be set in"
  echo "   hpb_deploy.config (your own roxmer/* repos, not the upstream one)."
  exit 1
fi

# ── Parse arguments ────────────────────────────────────────────────────────
RESET_DB=false
SKIP_PULL=false
RESTART_ONLY=false
PREV=""
for arg in "$@"; do
  case "$arg" in
    --reset-db) RESET_DB=true ;;
    --skip-pull) SKIP_PULL=true ;;
    --restart-services-only) RESTART_ONLY=true ;;
    --backend) ;;
    ollama|claude) BACKEND="$arg" ;;
    --backend=ollama) BACKEND="ollama" ;;
    --backend=claude) BACKEND="claude" ;;
    -h|--help)
      sed -n '2,60p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "❌ Unknown argument: $arg  (see --help)"
      exit 1
      ;;
  esac
  [ "$PREV" = "--backend" ] && BACKEND="$arg"
  PREV="$arg"
done
if [[ "$BACKEND" != "ollama" && "$BACKEND" != "claude" ]]; then
  echo "❌ Invalid backend: $BACKEND. Must be 'ollama' or 'claude'."
  exit 1
fi

BACKEND_LABEL="Local LLM via Ollama ($OLLAMA_MODEL)"
AGENT_FILE="api_agent_ollama.py"
AGENT_MODULE="api_agent_ollama"
[ "$BACKEND" = "claude" ] && BACKEND_LABEL="Anthropic Claude API"
[ "$BACKEND" = "claude" ] && AGENT_FILE="api_agent.py"
[ "$BACKEND" = "claude" ] && AGENT_MODULE="api_agent"

mkdir -p "$LOG_DIR" "$RUN_DIR"

# ── Helper: kill + restart the two background processes ──────────────────
restart_background_services() {
  echo "▶ Stopping any previous AI agent / sidecar processes..."
  if [ -f "$RUN_DIR/ai_agent.pid" ] && kill -0 "$(cat "$RUN_DIR/ai_agent.pid")" 2>/dev/null; then
    kill "$(cat "$RUN_DIR/ai_agent.pid")" 2>/dev/null || true
  fi
  if [ -f "$RUN_DIR/sidecar.pid" ] && kill -0 "$(cat "$RUN_DIR/sidecar.pid")" 2>/dev/null; then
    kill "$(cat "$RUN_DIR/sidecar.pid")" 2>/dev/null || true
  fi
  lsof -ti:"$AI_AGENT_PORT" | xargs -r kill -9 2>/dev/null || true
  lsof -ti:"$MOLECULAR_SIDECAR_PORT" | xargs -r kill -9 2>/dev/null || true
  sleep 2
  echo "✅ Ports cleared."

  if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
    echo "   AI Assistant disabled — not starting the Python AI Agent."
    AI_PID="(disabled)"
  else
    echo "▶ Starting Python AI Agent ($BACKEND_LABEL) on port $AI_AGENT_PORT..."
    cd "$AI_AGENT_DIR"
    source "$AI_AGENT_DIR/.venv/bin/activate"
    if [ "$BACKEND" = "claude" ]; then
      setsid env ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
          nohup uvicorn "$AGENT_MODULE:app" --host 0.0.0.0 --port "$AI_AGENT_PORT" \
          > "$LOG_DIR/agent.log" 2>&1 < /dev/null &
    else
      setsid nohup uvicorn "$AGENT_MODULE:app" --host 0.0.0.0 --port "$AI_AGENT_PORT" \
          > "$LOG_DIR/agent.log" 2>&1 < /dev/null &
    fi
    AI_PID=$!
    echo "$AI_PID" > "$RUN_DIR/ai_agent.pid"
    echo "✅ AI Agent started (PID: $AI_PID). Logs: $LOG_DIR/agent.log"
    sleep 4
    curl -s "http://127.0.0.1:$AI_AGENT_PORT/health" > /dev/null 2>&1 \
      && echo "✅ AI Agent health check passed." \
      || echo "⚠️  AI Agent did not respond yet — check $LOG_DIR/agent.log if issues arise"
  fi

  echo "▶ Starting molecular report parsing sidecar on port $MOLECULAR_SIDECAR_PORT..."
  if [ ! -d "$MOLECULAR_AGENT_DIR" ]; then
    echo "⚠️  $MOLECULAR_AGENT_DIR not found — skipping sidecar."
  else
    if python3 -c "import sys; sys.exit(0 if sys.prefix == sys.base_prefix else 1)"; then
      pip3 install --user --quiet -r "$MOLECULAR_AGENT_DIR/requirements.txt"
    else
      pip3 install --quiet -r "$MOLECULAR_AGENT_DIR/requirements.txt"
    fi
    cd "$MOLECULAR_AGENT_DIR"
    setsid nohup python3 service.py --port "$MOLECULAR_SIDECAR_PORT" \
        > "$LOG_DIR/sidecar.log" 2>&1 < /dev/null &
    SIDECAR_PID=$!
    echo "$SIDECAR_PID" > "$RUN_DIR/sidecar.pid"
    echo "✅ Report parsing sidecar started (PID: $SIDECAR_PID). Logs: $LOG_DIR/sidecar.log"
    sleep 2
    curl -s "http://127.0.0.1:$MOLECULAR_SIDECAR_PORT/health" > /dev/null 2>&1 \
      && echo "✅ Sidecar health check passed." \
      || echo "⚠️  Sidecar did not respond yet — check $LOG_DIR/sidecar.log"
  fi
}

echo ""
echo "======================================"
echo "  HPB-AI Server Deployment Starting..."
echo "  Server     : $SERVER_HOSTNAME"
echo "  Backend    : $BACKEND_LABEL"
echo "  Mode       : $([ "$RESTART_ONLY" = true ] && echo "restart services only" || echo "full deploy")"
[ "$RESET_DB" = true ] && echo "  Database   : RESET (drop + recreate)"
[ "$RESET_DB" = false ] && [ "$RESTART_ONLY" = false ] && echo "  Database   : kept as-is"
echo "======================================"
echo ""

# ── --restart-services-only short-circuit ─────────────────────────────────
if [ "$RESTART_ONLY" = true ]; then
  restart_background_services
  echo ""
  echo "✅ Done. Tomcat itself is unaffected (assumed already running via systemd)."
  exit 0
fi

# ── STEP 1: Backend-specific checks ───────────────────────────────────────
echo "▶ Step 1: Checking AI backend..."
if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
  echo "   AI Assistant disabled — skipping backend checks."
elif [ "$BACKEND" = "claude" ]; then
  [ -n "$ANTHROPIC_API_KEY" ] || { echo "❌ ANTHROPIC_API_KEY is empty in hpb_deploy.config."; exit 1; }
  echo "✅ Anthropic API key is set."
else
  curl -s "http://localhost:11434" > /dev/null 2>&1 || {
    echo "❌ Ollama is not running. Check: sudo systemctl status ollama"
    exit 1
  }
  echo "✅ Ollama server is running."
  MODEL_EXISTS=$(curl -s "http://localhost:11434/api/tags" | python3 -c \
    "import sys,json; tags=json.load(sys.stdin); \
     print('yes' if any('$OLLAMA_MODEL' in m['name'] for m in tags.get('models',[])) else 'no')" \
    2>/dev/null || echo "unknown")
  if [ "$MODEL_EXISTS" = "no" ]; then
    echo "⚠️  Model '$OLLAMA_MODEL' not pulled yet. Pulling now (may take several minutes)..."
    ollama pull "$OLLAMA_MODEL"
  fi
  echo "✅ Model '$OLLAMA_MODEL' available."
fi

# ── STEP 2: Java 21 ────────────────────────────────────────────────────────
echo ""
echo "▶ Step 2: Checking Java 21..."
JAVA_HOME=$(update-alternatives --list java 2>/dev/null | grep 'java-21' | sed 's#/bin/java##' | head -1)
[ -z "$JAVA_HOME" ] && [ -d "/usr/lib/jvm/java-21-openjdk-amd64" ] && JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
[ -n "$JAVA_HOME" ] || { echo "❌ Java 21 not found. Install with: sudo apt install openjdk-21-jdk"; exit 1; }
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"
echo "✅ Java version: $(java -version 2>&1 | head -1)"

# ── STEP 3: Maven ──────────────────────────────────────────────────────────
echo ""
echo "▶ Step 3: Checking Maven..."
mvn -version > /dev/null 2>&1 || { echo "❌ Maven not found."; exit 1; }
echo "✅ Maven is available."

# ── STEP 4: Pull latest code from your own repos ──────────────────────────
pull_repo() {
  local repo_url="$1" dir="$2" label="$3"
  if [ ! -d "$dir/.git" ]; then
    echo "   Cloning $label into $dir ..."
    mkdir -p "$(dirname "$dir")"
    git clone "$repo_url" "$dir"
  else
    cd "$dir"
    if [ -n "$(git status --porcelain)" ]; then
      echo "❌ $label ($dir) has uncommitted local changes on the server."
      echo "   Refusing to overwrite them with --skip-pull off. Either commit/stash"
      echo "   them, or re-run with --skip-pull to deploy what's already there."
      exit 1
    fi
    echo "   Pulling latest for $label..."
    git fetch origin
    git reset --hard "origin/$(git symbolic-ref --short HEAD)"
  fi
  cd "$dir"
  echo "   ✅ $label at $(git rev-parse --short HEAD) — $(git log -1 --format='%s')"
}

echo ""
if [ "$SKIP_PULL" = true ]; then
  echo "▶ Step 4: Skipped (--skip-pull) — deploying code already on disk."
else
  echo "▶ Step 4: Pulling latest code from your repos..."
  pull_repo "$HPB_APP_REPO" "$PROJECT_DIR" "HPB-AI (app)"
  pull_repo "$AI_AGENT_REPO" "$AI_AGENT_DIR" "ai-agent-hpb"
  pull_repo "$DEPLOY_ASSETS_REPO" "$DEPLOY_DIR" "HPB-AI-deploy (lookup lists + scripts)"
  echo "✅ All three repos up to date."
fi

# ── STEP 5: Sync environment-specific secrets (never stored in git) ──────
echo ""
echo "▶ Step 5: Syncing DB credentials + hostname into the build..."
PROPS_FILE="$PROJECT_DIR/src/main/resources/application.properties"
sed -i "s|^spring.datasource.password=.*|spring.datasource.password=$MYSQL_PASSWORD|" "$PROPS_FILE"
sed -i "s|^spring.datasource.username=.*|spring.datasource.username=$MYSQL_USER|" "$PROPS_FILE"
sed -i "s|^spring.datasource.url=jdbc:mysql://localhost:3306/.*|spring.datasource.url=jdbc:mysql://localhost:3306/$DB_NAME|" "$PROPS_FILE"
echo "✅ application.properties updated."

if [ "$ENABLE_AI_ASSISTANT" = "true" ]; then
  AGENT_PY_PATH="$AI_AGENT_DIR/$AGENT_FILE"
  [ -f "$AGENT_PY_PATH" ] || { echo "❌ $AGENT_PY_PATH not found."; exit 1; }
  python3 - "$AGENT_PY_PATH" "$MYSQL_PASSWORD" "$OLLAMA_MODEL" "$BACKEND" "$MYSQL_USER" "$DB_NAME" << 'PYEOF'
import re, sys
path, mysql_password, ollama_model, backend, mysql_user, db_name = sys.argv[1:7]
with open(path, "r") as f:
    content = f.read()
content = re.sub(r'("password"\s*:\s*)"[^"]*"',
                  lambda m: m.group(1) + '"' + mysql_password.replace('\\', '\\\\').replace('"', '\\"') + '"',
                  content, count=1)
content = re.sub(r'("user"\s*:\s*)"[^"]*"',
                  lambda m: m.group(1) + '"' + mysql_user.replace('\\', '\\\\').replace('"', '\\"') + '"',
                  content, count=1)
content = re.sub(r'("database"\s*:\s*)"[^"]*"',
                  lambda m: m.group(1) + '"' + db_name.replace('\\', '\\\\').replace('"', '\\"') + '"',
                  content, count=1)
if backend == "ollama":
    content = re.sub(r'(MODEL_NAME\s*=\s*)"[^"]*"',
                      lambda m: m.group(1) + '"' + ollama_model + '"',
                      content, count=1)
with open(path, "w") as f:
    f.write(content)
print("   ✅ AI agent DB config + model synced")
PYEOF
fi

# ── STEP 6: Generate deploy_HPB/.env for the lookup-list importer ────────
echo ""
echo "▶ Step 6: Writing deploy_HPB/.env for imports_fixed.sh..."
cat > "$DEPLOY_DIR/.env" << ENVEOF
BASE_URL=http://localhost:$TOMCAT_PORT/hpb
HPB_ADMIN_USERNAME=$IMPORT_USERNAME
HPB_ADMIN_PASSWORD=$IMPORT_PASSWORD
ENVEOF
echo "✅ .env written."

# ── STEP 7: Check MySQL ────────────────────────────────────────────────────
echo ""
echo "▶ Step 7: Checking MySQL..."
mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -h 127.0.0.1 -e "SELECT 1;" > /dev/null 2>&1 || {
  echo "❌ Could not connect to MySQL as $MYSQL_USER with the password in hpb_deploy.config."
  exit 1
}
echo "✅ MySQL is running and reachable."

# ── STEP 8: Reset OR ensure database exists ───────────────────────────────
echo ""
if [ "$RESET_DB" = true ]; then
  echo "▶ Step 8: Resetting database (--reset-db)..."
  mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -h 127.0.0.1 -e "DROP DATABASE IF EXISTS $DB_NAME; CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4;"
  echo "✅ Database '$DB_NAME' recreated. Flyway will build the schema from scratch on redeploy."
else
  echo "▶ Step 8: Checking database exists (keeping any existing data)..."
  DB_EXISTS=$(mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -h 127.0.0.1 -e "SHOW DATABASES LIKE '$DB_NAME';" 2>/dev/null | grep "$DB_NAME" || true)
  if [ -z "$DB_EXISTS" ]; then
    echo "   Database '$DB_NAME' not found — creating it (first run on this server)..."
    mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -h 127.0.0.1 -e "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4;"
  fi
  echo "✅ Database '$DB_NAME' present — existing data kept."
fi

# ── STEP 9: Build ──────────────────────────────────────────────────────────
echo ""
echo "▶ Step 9: Running Maven clean install..."
cd "$PROJECT_DIR"
mvn clean install -DskipTests
WAR_FILE=$(find "$PROJECT_DIR/target" -maxdepth 1 -name "*.war" ! -name "*.original" | head -1)
[ -n "$WAR_FILE" ] || { echo "❌ No .war file found in $PROJECT_DIR/target after build."; exit 1; }
echo "✅ Build successful: $WAR_FILE"

# ── STEP 10: Swap the WAR into the shared Tomcat ──────────────────────────
echo ""
echo "▶ Step 10: Deploying into shared Tomcat ($TOMCAT_WEBAPPS_DIR/$TOMCAT_WAR_NAME)..."
echo "   (Only this one WAR is touched. tomcat.service itself is never restarted --"
echo "   the other apps sharing this Tomcat are unaffected.)"

BACKUP_NAME="$TOMCAT_WAR_NAME.backup_$(date +%Y%m%d_%H%M%S)"
if [ -f "$TOMCAT_WEBAPPS_DIR/$TOMCAT_WAR_NAME" ]; then
  sudo cp "$TOMCAT_WEBAPPS_DIR/$TOMCAT_WAR_NAME" "$HOME/$BACKUP_NAME"
  echo "   Backed up current WAR to ~/$BACKUP_NAME"
fi

MARKER_LINE=$(sudo wc -l < "$CATALINA_LOG" 2>/dev/null || echo 0)
sudo cp "$WAR_FILE" "$TOMCAT_WEBAPPS_DIR/$TOMCAT_WAR_NAME"
echo "   WAR copied — waiting for Tomcat to auto-redeploy (up to 3 minutes)..."

DEPLOY_OK=false
for i in $(seq 1 90); do
  sleep 2
  NEW_LINES=$(sudo tail -n +"$((MARKER_LINE + 1))" "$CATALINA_LOG" 2>/dev/null || true)
  if echo "$NEW_LINES" | grep -q "Deployment of web application archive \[$TOMCAT_WEBAPPS_DIR/$TOMCAT_WAR_NAME\] has finished"; then
    DEPLOY_OK=true
    break
  fi
  if echo "$NEW_LINES" | grep -qi "SEVERE.*$TOMCAT_WAR_NAME"; then
    echo "❌ Tomcat logged a SEVERE error while redeploying. Check: sudo tail -100 $CATALINA_LOG"
    exit 1
  fi
done

if [ "$DEPLOY_OK" = true ]; then
  echo "✅ Tomcat redeployed successfully."
else
  echo "⚠️  Didn't see the 'finished' line within 3 minutes — check manually:"
  echo "   sudo tail -f $CATALINA_LOG"
fi

sleep 3
curl -s -o /dev/null -w "   App HTTP status: %{http_code}\n" "http://127.0.0.1:$TOMCAT_PORT/hpb/" || true

# ── STEP 11: Reload lookup lists ──────────────────────────────────────────
echo ""
echo "▶ Step 11: Reloading lookup lists (import.csv)..."
cd "$DEPLOY_DIR"
chmod +x imports_fixed.sh
./imports_fixed.sh import.csv || echo "   ⚠️  Some lists reported failures above -- 'duplicate' failures are expected"
echo "   and harmless on a database that already has data; check any other kind"
echo "   of failure manually."

# ── STEP 12: Restart AI agent + sidecar ───────────────────────────────────
echo ""
echo "▶ Step 12: Restarting AI agent + report-parsing sidecar..."
restart_background_services

echo ""
echo "======================================"
echo "  HPB Application Deployed"
echo "  Backend    : $BACKEND_LABEL"
echo "  App URL    : https://$SERVER_HOSTNAME/"
[ "$ENABLE_AI_ASSISTANT" = "true" ] && echo "  AI Agent   : https://$SERVER_HOSTNAME/ai-agent/health"
echo "  Logs       : $LOG_DIR/   and   sudo tail -f $CATALINA_LOG"
echo "======================================"
echo ""
echo "This script does NOT populate synthetic/test patient data on purpose."
echo "To load test data, see the deployment runbook (Part D) and run the"
echo "synthetic_test_patients*.sql scripts manually against $DB_NAME."
echo ""
