#!/bin/bash
# ==============================================================================
#   HPB-AI Server Deployment Script — Multi-Backend
#   (Server edition of deploy_hpb_local.sh — adapted for a Linux VM,
#    reads all settings from hpb_deploy.config instead of hardcoded values.)
#
#   DO NOT EDIT THIS FILE. All settings live in hpb_deploy.config, in the
#   same folder as this script. Edit that file instead.
#
#   Supports two AI backends:
#     --backend ollama   (default, or whatever BACKEND= says in the config)
#                        Local LLM via Ollama — no API key needed, no patient
#                        data leaves this server.
#     --backend claude   Anthropic Claude API — requires ANTHROPIC_API_KEY
#                        set in hpb_deploy.config.
#
#   Database modes:
#     (default)          Reset database
#     --keep-db / -k     Keep existing database data
#
#   AI Assistant:
#     Controlled by ENABLE_AI_ASSISTANT in hpb_deploy.config (default
#     "true"). Set to "false" to deploy the core registry + report-parsing
#     sidecar only, without Ollama/Claude checks or the AI Assistant menu
#     entry. The report-parsing sidecar (PDF/JSON Analysis import) is
#     always deployed regardless of this setting.
#
#   Usage examples:
#     ./deploy_hpb_server.sh                    Ollama backend, resets the DB
#     ./deploy_hpb_server.sh --keep-db          Ollama backend, keeps the DB
#     ./deploy_hpb_server.sh --backend claude   Claude backend, resets the DB
#
#   Before first run: chmod +x deploy_hpb_server.sh
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/hpb_deploy.config"

# ── STEP 0: Load configuration ────────────────────────────────────────────
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ Config file not found: $CONFIG_FILE"
  echo "   Make sure hpb_deploy.config is in the same folder as this script."
  exit 1
fi
# shellcheck disable=SC1090
source "$CONFIG_FILE"

# Default MYSQL_USER to root for backward compatibility with configs that
# don't set it (older deployments, or local dev where root is fine).
MYSQL_USER="${MYSQL_USER:-root}"

# Sanity-check the handful of settings that MUST be changed from their
# placeholder values before this script is allowed to run.
if [ "$MYSQL_PASSWORD" = "CHANGE_ME_TO_A_STRONG_PASSWORD" ] || [ -z "$MYSQL_PASSWORD" ]; then
  echo "❌ MYSQL_PASSWORD in hpb_deploy.config is still the placeholder value."
  echo "   Set a real password there first (see Section 3 of the guide)."
  exit 1
fi
if [ "$SERVER_HOSTNAME" = "hpb-test.example.ki.se" ]; then
  echo "⚠️  SERVER_HOSTNAME in hpb_deploy.config is still the example placeholder."
  echo "   The AI Assistant page will not work for the clinician until this is"
  echo "   set to this server's real hostname or IP. Continuing anyway..."
fi

# ── Parse arguments (can override BACKEND / add --keep-db) ───────────────
KEEP_DB=false
LOCAL_ONLY=false   # default: false = clone fresh from the programmers' repo,
                   # as before. true (--local-only) = skip that clone entirely
                   # and deploy $PROJECT_DIR exactly as it sits on disk (e.g.
                   # rsynced from your own machine) -- no clone, nothing from
                   # kiehealth/11.-HPB overwrites it.
[ -n "$BACKEND" ] || BACKEND="ollama"
[ -n "$ENABLE_AI_ASSISTANT" ] || ENABLE_AI_ASSISTANT="true"
[ -n "$MOLECULAR_AGENT_DIR" ] || MOLECULAR_AGENT_DIR="$PARENT_DIR/molecular_report_agent"
[ -n "$MOLECULAR_SIDECAR_PORT" ] || MOLECULAR_SIDECAR_PORT=8090

for arg in "$@"; do
  case "$arg" in
    --keep-db|-k) KEEP_DB=true ;;
    --local-only) LOCAL_ONLY=true ;;
    --backend) ;;  # handled by shift-scan below
    ollama|claude) BACKEND="$arg" ;;
    --backend=ollama) BACKEND="ollama" ;;
    --backend=claude) BACKEND="claude" ;;
    *)
      echo "❌ Unknown argument: $arg"
      echo "   Usage: ./deploy_hpb_server.sh [--backend ollama|claude] [--keep-db|-k] [--local-only]"
      exit 1
      ;;
  esac
done
for i in "$@"; do
  if [ "$PREV" = "--backend" ]; then BACKEND="$i"; fi
  PREV="$i"
done

if [[ "$BACKEND" != "ollama" && "$BACKEND" != "claude" ]]; then
  echo "❌ Invalid backend: $BACKEND. Must be 'ollama' or 'claude'."
  exit 1
fi

DB_LABEL="(Reset Database)"
[ "$KEEP_DB" = true ] && DB_LABEL="(Keeping existing database data)"

BACKEND_LABEL="Local LLM via Ollama ($OLLAMA_MODEL)"
AGENT_FILE="api_agent_ollama.py"
AGENT_MODULE="api_agent_ollama"
[ "$BACKEND" = "claude" ] && BACKEND_LABEL="Anthropic Claude API"
[ "$BACKEND" = "claude" ] && AGENT_FILE="api_agent.py"
[ "$BACKEND" = "claude" ] && AGENT_MODULE="api_agent"

echo ""
echo "======================================"
echo "  HPB-AI Server Deployment Starting..."
echo "  Server     : $SERVER_HOSTNAME"
echo "  Backend    : $BACKEND_LABEL"
if [ "$LOCAL_ONLY" = true ]; then
  echo "  Source     : LOCAL ONLY -- deploying \$PROJECT_DIR as-is, no clone from PROGRAMMERS_REPO"
else
  echo "  Source     : $PROGRAMMERS_REPO (fresh clone)"
fi
echo "  $DB_LABEL"
echo "======================================"
echo ""

mkdir -p "$LOG_DIR" "$RUN_DIR"

# ── STEP 1: Backend-specific checks ───────────────────────────────────────
echo "▶ Step 1: Checking AI backend..."

if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
  echo "   AI Assistant disabled (ENABLE_AI_ASSISTANT=\"$ENABLE_AI_ASSISTANT\") — skipping backend checks."
elif [ "$BACKEND" = "claude" ]; then
  if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo "❌ ANTHROPIC_API_KEY is empty in hpb_deploy.config. Set it and re-run."
    exit 1
  fi
  TRIMMED_KEY=$(echo "$ANTHROPIC_API_KEY" | xargs)
  if [ "$ANTHROPIC_API_KEY" != "$TRIMMED_KEY" ]; then
    echo "⚠️  API key has leading/trailing whitespace — trimming for this run."
    ANTHROPIC_API_KEY="$TRIMMED_KEY"
  fi
  echo "✅ Anthropic API key is set and clean."
else
  curl -s "http://localhost:11434" > /dev/null 2>&1 || {
    echo "❌ Ollama is not running. Check it with: sudo systemctl status ollama"
    echo "   If it's not installed yet, see Section 2.5 of the guide."
    exit 1
  }
  echo "✅ Ollama server is running."

  MODEL_EXISTS=$(curl -s "http://localhost:11434/api/tags" | python3 -c \
    "import sys,json; tags=json.load(sys.stdin); \
     print('yes' if any('$OLLAMA_MODEL' in m['name'] for m in tags.get('models',[])) else 'no')" \
    2>/dev/null || echo "unknown")

  if [ "$MODEL_EXISTS" = "no" ]; then
    echo "⚠️  Model '$OLLAMA_MODEL' is not pulled yet. Pulling now..."
    echo "   (This downloads several GB — may take several minutes)"
    ollama pull "$OLLAMA_MODEL"
    echo "✅ Model pulled successfully."
  elif [ "$MODEL_EXISTS" = "yes" ]; then
    echo "✅ Model '$OLLAMA_MODEL' is available."
  else
    echo "⚠️  Could not verify model — continuing anyway."
  fi
fi

# ── STEP 2: Java 21 ────────────────────────────────────────────────────────
echo ""
echo "▶ Step 2: Checking Java 21..."
JAVA_HOME=$(update-alternatives --list java 2>/dev/null | grep 'java-21' | sed 's#/bin/java##' | head -1)
if [ -z "$JAVA_HOME" ] && [ -d "/usr/lib/jvm/java-21-openjdk-amd64" ]; then
  JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64"
fi
if [ -z "$JAVA_HOME" ]; then
  echo "❌ Java 21 not found. Install with: sudo apt install openjdk-21-jdk"
  exit 1
fi
export JAVA_HOME
export PATH="$JAVA_HOME/bin:$PATH"
echo "✅ Java version: $(java -version 2>&1 | head -1)"

# ── STEP 3: Maven ──────────────────────────────────────────────────────────
echo ""
echo "▶ Step 3: Checking Maven..."
mvn -version > /dev/null 2>&1 || {
  echo "❌ Maven not found. See Section 2.3 of the guide for the manual install steps."
  exit 1
}
MVN_VERSION=$(mvn -version 2>/dev/null | head -1 | awk '{print $3}')
echo "✅ Maven is available (version $MVN_VERSION)."

# ── STEP 4: Clone programmers' repo fresh (skipped in --local-only) ──────
echo ""
if [ "$LOCAL_ONLY" = true ]; then
  echo "▶ Step 4: Skipped (--local-only) -- deploying $PROJECT_DIR as-is."
  if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ --local-only requires $PROJECT_DIR to already exist -- there's nothing"
    echo "   to deploy. Copy your local 11.-HPB folder onto the server first, or"
    echo "   run without --local-only at least once."
    exit 1
  fi
  cd "$PROJECT_DIR"
  if git rev-parse --git-dir > /dev/null 2>&1; then
    echo "   Deployed commit : $(git rev-parse --short HEAD 2>/dev/null)  — $(git log -1 --format='%s' 2>/dev/null) (+ uncommitted local changes, if any)"
  fi
else
  echo "▶ Step 4: Cloning latest code from programmers' repo..."
  if [ -d "$PROJECT_DIR" ]; then
    echo "   Removing existing folder..."
    rm -rf "$PROJECT_DIR"
  fi
  mkdir -p "$PARENT_DIR"
  cd "$PARENT_DIR"
  git clone "$PROGRAMMERS_REPO" "$PROJECT_DIR"
  echo "✅ Programmers' repo cloned successfully."
fi

NAVUTIL="$PROJECT_DIR/src/main/resources/static/js/util/NavUtil.js"

# ── STEP 5: Regenerate Maven wrapper ──────────────────────────────────────
echo ""
echo "▶ Step 5: Regenerating Maven wrapper..."
cd "$PROJECT_DIR"
mvn -N io.takari:maven:wrapper > /dev/null 2>&1
echo "✅ Maven wrapper regenerated."

# ── STEP 6: Apply AI Assistant files ──────────────────────────────────────
echo ""
if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
  echo "▶ Step 6: AI Assistant disabled — skipping AI Assistant files, NavUtil.js and SecurityConfig.java patches."
else
echo "▶ Step 6: Applying AI Assistant files..."

cp "$AI_AGENT_DIR/ai-assistant.html" \
   "$PROJECT_DIR/src/main/resources/static/ai-assistant.html"
echo "   ✅ ai-assistant.html copied"

mkdir -p "$PROJECT_DIR/src/main/resources/static/js/view"
cp "$AI_AGENT_DIR/AiAssistantView.js" \
   "$PROJECT_DIR/src/main/resources/static/js/view/AiAssistantView.js"

VIEW_JS_TARGET="$PROJECT_DIR/src/main/resources/static/js/view/AiAssistantView.js"

# ── NOTE ──────────────────────────────────────────────────────────────────
# AiAssistantView.js now sets AI_AGENT_URL to window.location.origin + '/ai-agent'
# (a relative path), so it needs no per-server substitution: whatever hostname
# loaded the page is reused automatically. This relies on the Apache vhost
# proxying /ai-agent/ to http://127.0.0.1:${AI_AGENT_PORT}/ (set up once,
# outside this script -- see the deployment runbook).
if grep -q "window.location.origin + '/ai-agent'" "$VIEW_JS_TARGET"; then
  echo "   ✅ AiAssistantView.js copied (relative AI_AGENT_URL, no patching needed)"
else
  echo "   ❌ ERROR: AiAssistantView.js template is missing the expected relative AI_AGENT_URL"
  exit 1
fi

python3 - "$NAVUTIL" << 'PYEOF'
import sys

navutil_path = sys.argv[1]

with open(navutil_path, "r") as f:
    content = f.read()

changed = False

menu_entry = "{id: 'AiAssistant', icon: 'fas fa-robot', title: 'AI Assistant', authority: 'AI_ASSISTANT', page: 'ai-assistant.html'},"

if "id: 'AiAssistant'" not in content:
    anchor = "{id: 'Patient', icon: 'fas fa-user-injured', title: 'Patient', authority: 'PATIENT', page: 'patient.html'},"
    if anchor not in content:
        print("   ❌ ERROR: Could not find anchor line for menu entry in NavUtil.js")
        sys.exit(1)
    content = content.replace(anchor, anchor + "\n        " + menu_entry, 1)
    changed = True
    print("   ✅ Menu entry added to mainItems")
else:
    print("   ℹ️  Menu entry already present — skipping (idempotent)")

if "AI Assistant forced visible" not in content:
    target = "static showFullNavigation() {"
    if target not in content:
        print("   ❌ ERROR: Could not find showFullNavigation() in NavUtil.js")
        sys.exit(1)

    import re
    method_match = re.search(r"static showFullNavigation\(\)\s*\{(.*?)\n\s*\}", content, re.DOTALL)
    if not method_match:
        print("   ❌ ERROR: Could not parse showFullNavigation() body")
        sys.exit(1)

    body = method_match.group(1)
    ai_block = """
        // Always show AI Assistant regardless of authority
        const aiContainer = document.querySelector('#linkAiAssistantContainer');
        const aiLink      = document.querySelector('#linkAiAssistant');
        if (aiContainer && aiLink) {
            aiContainer.hidden = false;
            aiLink.href = `${EndPoints.BASE_URL}/ai-assistant.html`;
            console.log("AI Assistant forced visible");
        }"""

    new_body = body + ai_block
    content = content.replace(
        "static showFullNavigation() {" + body + "\n    }",
        "static showFullNavigation() {" + new_body + "\n    }",
        1
    )
    changed = True
    print("   ✅ Force-show block added to showFullNavigation()")
else:
    print("   ℹ️  Force-show block already present — skipping (idempotent)")

if changed:
    with open(navutil_path, "w") as f:
        f.write(content)

with open(navutil_path, "r") as f:
    final_content = f.read()

ok = True
if "id: 'AiAssistant'" not in final_content:
    print("   ❌ VERIFICATION FAILED: menu entry missing after patch")
    ok = False
if "AI Assistant forced visible" not in final_content:
    print("   ❌ VERIFICATION FAILED: force-show block missing after patch")
    ok = False

count = final_content.count("id: 'AiAssistant'")
if count > 1:
    print(f"   ❌ VERIFICATION FAILED: {count} duplicate AiAssistant entries found!")
    ok = False

if not ok:
    sys.exit(1)

print("   ✅ Verification passed — NavUtil.js correctly patched")
PYEOF

if [ $? -ne 0 ]; then
    echo "❌ NavUtil.js patching failed."
    exit 1
fi

SECURITY_CONFIG=$(find "$PROJECT_DIR/src/main/java" -name "SecurityConfig.java" | head -1)
if [ -n "$SECURITY_CONFIG" ]; then
    if grep -q "/ai-assistant.html" "$SECURITY_CONFIG"; then
        echo "   ℹ️  SecurityConfig.java already permits /ai-assistant.html — skipping"
    else
        sed -i 's|"/user_profile.html",|"/user_profile.html", "/ai-assistant.html",|' "$SECURITY_CONFIG"
        if grep -q "/ai-assistant.html" "$SECURITY_CONFIG"; then
            echo "   ✅ SecurityConfig.java updated"
        else
            echo "   ❌ ERROR: Could not patch SecurityConfig.java"
            exit 1
        fi
    fi
else
    echo "   ❌ ERROR: SecurityConfig.java not found"
    exit 1
fi

echo "✅ All AI Assistant files applied and verified."
fi

# ── STEP 6b: Apply backend bug-fix patches (TEMPORARY) ────────────────────
#   Source of truth: $AI_AGENT_DIR/backend_patches/ (mirrors exact repo-
#   relative paths). Remove this step once the programmers have merged the
#   fix into kiehealth/11.-HPB. See Section 5 of the guide for details on
#   why this folder exists and what happens if it's skipped.
echo ""
echo "▶ Step 6b: Applying backend bug-fix patches (temporary, pending upstream merge)..."

BACKEND_PATCHES_DIR="$AI_AGENT_DIR/backend_patches"

if [ -d "$BACKEND_PATCHES_DIR" ]; then
    PATCH_COUNT=0
    while IFS= read -r -d '' patch_file; do
        rel_path="${patch_file#$BACKEND_PATCHES_DIR/}"
        target_path="$PROJECT_DIR/$rel_path"
        mkdir -p "$(dirname "$target_path")"
        cp "$patch_file" "$target_path"
        echo "   ✅ $rel_path"
        PATCH_COUNT=$((PATCH_COUNT + 1))
    done < <(find "$BACKEND_PATCHES_DIR" -type f -print0)
    echo "✅ Applied $PATCH_COUNT backend patch file(s)."
else
    echo "   ℹ️  No backend_patches folder found — skipping (nothing to apply)."
fi

# ── STEP 7: Update application.properties ─────────────────────────────────
echo ""
echo "▶ Step 7: Updating application.properties (DB password + port)..."
PROPS_FILE="$PROJECT_DIR/src/main/resources/application.properties"
sed -i "s|^spring.datasource.password=.*|spring.datasource.password=$MYSQL_PASSWORD|" "$PROPS_FILE"
sed -i "s|^spring.datasource.username=.*|spring.datasource.username=$MYSQL_USER|" "$PROPS_FILE"
sed -i "s|^spring.datasource.url=jdbc:mysql://localhost:3306/.*|spring.datasource.url=jdbc:mysql://localhost:3306/$DB_NAME|" "$PROPS_FILE"
sed -i "s|^server.port=.*|server.port=$SPRING_PORT|" "$PROPS_FILE"
echo "✅ application.properties updated (datasource URL, username, password, port)."

# ── STEP 8: Update the AI Agent's own DB password + model name ───────────
# api_agent.py / api_agent_ollama.py each keep their own DB_CONFIG password
# hardcoded in the source file (they are not read from application.properties).
# This step keeps that in sync with hpb_deploy.config automatically instead
# of requiring a manual edit inside the Python file on every deploy.
echo ""
if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
  echo "▶ Step 8: AI Assistant disabled — skipping AI Agent DB/model sync."
else
echo "▶ Step 8: Syncing AI Agent DB user/password/database / model with hpb_deploy.config..."
AGENT_PY_PATH="$AI_AGENT_DIR/$AGENT_FILE"
if [ ! -f "$AGENT_PY_PATH" ]; then
  echo "❌ ERROR: $AGENT_PY_PATH not found."
  exit 1
fi

python3 - "$AGENT_PY_PATH" "$MYSQL_PASSWORD" "$OLLAMA_MODEL" "$BACKEND" "$MYSQL_USER" "$DB_NAME" << 'PYEOF'
import re, sys

path, mysql_password, ollama_model, backend, mysql_user, db_name = sys.argv[1:7]

with open(path, "r") as f:
    content = f.read()

new_content, n = re.subn(
    r'("password"\s*:\s*)"[^"]*"',
    lambda m: m.group(1) + '"' + mysql_password.replace('\\', '\\\\').replace('"', '\\"') + '"',
    content,
    count=1,
)
if n == 1:
    print("   ✅ DB_CONFIG password synced")
else:
    print("   ⚠️  Could not find a DB_CONFIG password field to patch — check manually")
content = new_content

new_content, n = re.subn(
    r'("user"\s*:\s*)"[^"]*"',
    lambda m: m.group(1) + '"' + mysql_user.replace('\\', '\\\\').replace('"', '\\"') + '"',
    content,
    count=1,
)
if n == 1:
    print("   ✅ DB_CONFIG user synced")
else:
    print("   ⚠️  Could not find a DB_CONFIG user field to patch — check manually")
content = new_content

new_content, n = re.subn(
    r'("database"\s*:\s*)"[^"]*"',
    lambda m: m.group(1) + '"' + db_name.replace('\\', '\\\\').replace('"', '\\"') + '"',
    content,
    count=1,
)
if n == 1:
    print("   ✅ DB_CONFIG database synced")
else:
    print("   ⚠️  Could not find a DB_CONFIG database field to patch — check manually")
content = new_content

if backend == "ollama":
    updated, n2 = re.subn(
        r'(MODEL_NAME\s*=\s*)"[^"]*"',
        lambda m: m.group(1) + '"' + ollama_model + '"',
        content,
        count=1,
    )
    if n2 == 1:
        print(f"   ✅ MODEL_NAME synced to {ollama_model}")
        content = updated
    else:
        print("   ⚠️  Could not find MODEL_NAME to patch — check manually")

with open(path, "w") as f:
    f.write(content)
PYEOF
echo "✅ AI Agent source file synced."
fi

# ── STEP 9: Push merged result to your HPB-AI repo (optional) ────────────
echo ""
if [ -n "$YOUR_REPO" ]; then
  echo "▶ Step 9: Pushing merged result to $YOUR_REPO ..."
  cd "$PROJECT_DIR"
  git config user.name "$GIT_USER_NAME"
  git config user.email "$GIT_USER_EMAIL"
  git remote add origin "$YOUR_REPO" 2>/dev/null || git remote set-url origin "$YOUR_REPO"
  git add .
  git commit -m "Server deploy: merge programmers + AI Assistant [backend: $BACKEND] $(date '+%Y-%m-%d %H:%M')" --no-edit || echo "   (Nothing new to commit)"
  git push origin main --force
  echo "✅ Pushed to HPB-AI repo."
else
  echo "▶ Step 9: YOUR_REPO is blank in hpb_deploy.config — skipping git push."
fi

# ── STEP 10: Check MySQL ───────────────────────────────────────────────────
echo ""
echo "▶ Step 10: Checking MySQL..."
mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -e "SELECT 1;" > /dev/null 2>&1 || {
  echo "❌ Could not connect to MySQL as root with the password in hpb_deploy.config."
  echo "   If this is the very first deploy on this server, complete the one-time"
  echo "   MySQL setup in Section 3 of the guide first."
  exit 1
}
echo "✅ MySQL is running and reachable."

# ── STEP 11: Reset OR keep database ────────────────────────────────────────
echo ""
if [ "$KEEP_DB" = true ]; then
  echo "▶ Step 11: Checking database (keep-db mode)..."
  DB_EXISTS=$(mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -e "SHOW DATABASES LIKE '$DB_NAME';" 2>/dev/null | grep "$DB_NAME" || true)
  if [ -z "$DB_EXISTS" ]; then
    echo "   Database '$DB_NAME' not found — creating it..."
    mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -e "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4;"
    echo "✅ Database '$DB_NAME' created."
  else
    echo "✅ Database '$DB_NAME' exists — keeping existing data."
  fi

  echo ""
  echo "▶ Step 11b: Running Flyway repair..."
  cd "$PROJECT_DIR"
  mvn flyway:repair \
    -Dflyway.url=jdbc:mysql://localhost:3306/$DB_NAME \
    -Dflyway.user="$MYSQL_USER" \
    -Dflyway.password="$MYSQL_PASSWORD" 2>/dev/null || echo "   (Flyway repair not needed, continuing...)"
  echo "✅ Flyway repair done."
else
  echo "▶ Step 11: Resetting database..."
  mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --protocol=TCP -e "DROP DATABASE IF EXISTS $DB_NAME; CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4;"
  echo "✅ Database '$DB_NAME' recreated."
fi

# ── STEP 12: Build ──────────────────────────────────────────────────────────
echo ""
echo "▶ Step 12: Running Maven clean install..."
cd "$PROJECT_DIR"
mvn clean install -DskipTests
echo "✅ Build successful."

# ── STEP 13: Stop anything already running ─────────────────────────────────
echo ""
echo "▶ Step 13: Stopping any previous HPB-AI processes..."
if [ -f "$RUN_DIR/ai_agent.pid" ] && kill -0 "$(cat "$RUN_DIR/ai_agent.pid")" 2>/dev/null; then
  kill "$(cat "$RUN_DIR/ai_agent.pid")" 2>/dev/null || true
fi
if [ -f "$RUN_DIR/springboot.pid" ] && kill -0 "$(cat "$RUN_DIR/springboot.pid")" 2>/dev/null; then
  kill "$(cat "$RUN_DIR/springboot.pid")" 2>/dev/null || true
fi
if [ -f "$RUN_DIR/sidecar.pid" ] && kill -0 "$(cat "$RUN_DIR/sidecar.pid")" 2>/dev/null; then
  kill "$(cat "$RUN_DIR/sidecar.pid")" 2>/dev/null || true
fi
lsof -ti:"$AI_AGENT_PORT" | xargs -r kill -9 2>/dev/null || true
lsof -ti:"$SPRING_PORT"   | xargs -r kill -9 2>/dev/null || true
lsof -ti:"$MOLECULAR_SIDECAR_PORT" | xargs -r kill -9 2>/dev/null || true
sleep 2
echo "✅ Ports cleared."

# ── STEP 14: Start AI Agent (backgrounded, survives SSH logout) ───────────
echo ""
if [ "$ENABLE_AI_ASSISTANT" != "true" ]; then
  echo "▶ Step 14: AI Assistant disabled — not starting the Python AI Agent."
  AI_PID="(disabled)"
else
echo "▶ Step 14: Starting Python AI Agent ($BACKEND_LABEL) on port $AI_AGENT_PORT..."
cd "$AI_AGENT_DIR"
source "$AI_AGENT_DIR/.venv/bin/activate"

if [ "$BACKEND" = "claude" ]; then
  setsid env ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
      nohup uvicorn "$AGENT_MODULE:app" --host 0.0.0.0 --port "$AI_AGENT_PORT" \
      > "$LOG_DIR/agent.log" 2>&1 < /dev/null &
else
  setsid nohup uvicorn "$AGENT_MODULE:app" --host 0.0.0.0 --port "$AI_AGENT_PORT" \
      > "$LOG_DIR/agent.log" 2>&1 < /dev/null &
fi

AI_PID=$!
echo "$AI_PID" > "$RUN_DIR/ai_agent.pid"
echo "✅ AI Agent started (PID: $AI_PID). Logs: $LOG_DIR/agent.log"
sleep 4

curl -s "http://localhost:$AI_AGENT_PORT/health" > /dev/null 2>&1 \
  && echo "✅ AI Agent health check passed." \
  || echo "⚠️  AI Agent did not respond yet — check $LOG_DIR/agent.log if issues arise"
fi

# ── STEP 15: Build + start SpringBoot as a background process ────────────
echo ""
echo "▶ Step 15: Starting SpringBoot on port $SPRING_PORT..."
cd "$PROJECT_DIR"
APP_JAR=$(find "$PROJECT_DIR/target" -maxdepth 1 \( -name "*.jar" -o -name "*.war" \) ! -name "*.original" | head -1)
if [ -z "$APP_JAR" ]; then
  echo "❌ ERROR: No runnable .jar or .war found in $PROJECT_DIR/target after the build."
  exit 1
fi

setsid nohup java -jar "$APP_JAR" \
    > "$LOG_DIR/springboot.log" 2>&1 < /dev/null &
SPRING_PID=$!
echo "$SPRING_PID" > "$RUN_DIR/springboot.pid"
echo "✅ SpringBoot started (PID: $SPRING_PID). Logs: $LOG_DIR/springboot.log"

# ── STEP 15b: Start molecular report parsing sidecar ──────────────────────
#   Independent of ENABLE_AI_ASSISTANT above -- always started. Parses an
#   uploaded genomic/molecular PDF report (Add Analysis -> Parse from PDF)
#   into the same JSON shape a manual/JSON-import entry uses. Not an AI
#   model -- a pdfplumber-based template parser (molecular_report_agent/).
#   Every result lands as PENDING_REVIEW for a person to check against the
#   source PDF; nothing it produces is ever saved automatically.
echo ""
echo "▶ Step 15b: Starting molecular report parsing sidecar on port $MOLECULAR_SIDECAR_PORT..."
if [ ! -d "$MOLECULAR_AGENT_DIR" ]; then
  echo "❌ ERROR: $MOLECULAR_AGENT_DIR not found."
  echo "   Copy the molecular_report_agent folder onto this server first (it is"
  echo "   not in any git repo yet) -- see the guide's file-transfer section."
  exit 1
fi
if python3 -c "import sys; sys.exit(0 if sys.prefix == sys.base_prefix else 1)"; then
  pip3 install --user --quiet -r "$MOLECULAR_AGENT_DIR/requirements.txt"
else
  pip3 install --quiet -r "$MOLECULAR_AGENT_DIR/requirements.txt"
fi
cd "$MOLECULAR_AGENT_DIR"
setsid nohup python3 service.py --port "$MOLECULAR_SIDECAR_PORT" \
    > "$LOG_DIR/sidecar.log" 2>&1 < /dev/null &
SIDECAR_PID=$!
echo "$SIDECAR_PID" > "$RUN_DIR/sidecar.pid"
echo "✅ Report parsing sidecar started (PID: $SIDECAR_PID). Logs: $LOG_DIR/sidecar.log"
sleep 2

curl -s "http://localhost:$MOLECULAR_SIDECAR_PORT/health" > /dev/null 2>&1 \
  && echo "✅ Report parsing sidecar health check passed." \
  || echo "⚠️  Report parsing sidecar did not respond yet — check $LOG_DIR/sidecar.log if PDF/JSON parsing fails"

echo ""
echo "======================================"
echo "  HPB Application Deployed"
echo "  Backend    : $BACKEND_LABEL"
echo "  Mode       : $DB_LABEL"
echo "  SpringBoot : http://$SERVER_HOSTNAME:$SPRING_PORT   (PID $SPRING_PID)"
if [ "$ENABLE_AI_ASSISTANT" = "true" ]; then
echo "  AI Agent   : http://$SERVER_HOSTNAME:$AI_AGENT_PORT  (PID $AI_PID)"
echo "  AI Docs    : http://$SERVER_HOSTNAME:$AI_AGENT_PORT/docs"
else
echo "  AI Agent   : disabled (ENABLE_AI_ASSISTANT=\"false\" in hpb_deploy.config)"
fi
echo "  Sidecar    : http://localhost:$MOLECULAR_SIDECAR_PORT (PDF/JSON report parsing -- Java backend only, not browser-facing) (PID $SIDECAR_PID)"
echo "  Logs       : $LOG_DIR/"
echo "======================================"
echo ""
echo "SpringBoot can take 30-60 seconds to finish starting — tail the log to watch:"
echo "  tail -f $LOG_DIR/springboot.log"
echo ""
